language: common-lisp

env:
  matrix:
    - LISP=sbcl
    - LISP=sbcl32
    - LISP=ccl
    - LISP=ccl32
    - LISP=allegro
    - LISP=clisp
    - LISP=clisp32
    - LISP=ecl
    - LISP=abcl

install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
  - sudo apt-get update

script:
  - cl -e '(ql:quickload :cl-shellwords-test)'
       -e '(uiop:quit (if (asdf:test-system :cl-shellwords) 0 -1))'
